### PR TITLE
Support site_root_url placeholder in "default" preview client url

### LINKED ISSUE #16: HEADLESS_PREVIEW_CLIENT_URLS requires hardcoded hostnames
I use wagtail as a headless CMS for multiple sites. Having to hardcode hostnames in `HEADLESS_PREVIEW_CLIENT_URLS` is somewhat counter intuitive when the `Site` objects themselves live in the database and hostnames can be changed at will. 

I can think of other solutions that would work better (for me at least)

i.e. a template string:

`HEADLESS_PREVIEW_CLIENT_URL = '{root_url}/_cms_preview/` 

then `get_client_root_url` could `return HEADLESS_PREVIEW_CLIENT_URL.format(root_url=self.get_site().root_url)`

Or even a model that's related to `Site` and can be configured in the Wagtail settings interface.

Is this something you would consider? If so, which approach (or any other alternative) is preferred?

### PR DESCRIPTION
**Pull request by jaap3**
Fixes #16

I got stuck on updating the docs. Hope it's clear enough/acceptable

### CODE REVIEW

**Comment by jaap3** [comment]
The heck? The linting issue is on a line I didn't touch at all

**Comment by jaap3** [comment]
@zerolab are you interested in this?

**Comment by zerolab** [comment]
@jaap3 yes. it slipped under my radar. Will try to review this in the coming days!

**Comment by jaap3** [comment]
🔔 hope you get some time to review this before the one year anniversary ;-)

**Comment by zerolab** [comment]
@jaap3 adding to the list of things to check next week. Will give this package some much needed love and attention

**Comment by zerolab** [comment]
Hey @jaap3 merged in d184f7d3f74609f2bf77439aa6bfe758739cc153 and parents

I made a tweak in 91e8af4 that changed the placeholder to `{SITE_ROOT_URL}`

Will look at making a new release this afternoon

**Comment by jaap3** [comment]
Thank you!

**Pull request merged**
